[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && npm start"

[railway.variables]
NODE_ENV = "production"
PORT = "3000"
DB_HOST = "mysql.railway.internal"
DB_PORT = "3306"
DB_USER = "root"
DB_PASSWORD = "oKfkdwGVzjEolEkQlhfdoKBcbFOwaNsz"
DB_NAME = "railway"
JWT_SECRET = "elder_care_platform_secret_key_2026"
JWT_EXPIRES_IN = "7d"
CORS_ORIGIN = "*"
